site_name: DROP
nav:
    - Getting started: index.md
    - Architecture: architecture.md
    - Tools: tools.md
    - Plugins: plugins.md
    - Examples: examples.md
    - FAQ: faq.md
    - Tutorials: tutor.md
theme: readthedocs
