site_name: DROP
nav:
    - Getting started: index.md
    - Architecture: architecture.md
    - Tools: tools.md
    - Plugins: plugins.md
    - Examples: examples.md
    - FAQs: facs.md
    - Totorials: tutor.md
theme: readthedocs

